name: PHP Code Quality

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "Validate composer.json and composer.lock"
        run: composer validate

      - name: "Install dependencies"
        run: composer install --prefer-dist --no-progress

      - name: "Run test suite"
        run: composer run-script test

      - name: "Check coding standards"
        if: ${{ matrix.php-version != '8.4' }}
        run: "vendor/bin/php-cs-fixer fix -v --dry-run"
